### ISSUE TITLE
Dynamic UBOs are too small.

### ISSUE THREAD

**Issue by BNieuwenhuizen** [janhsimon/Makma#2]
Hi, due to you mentioning that this project renders a black screen with radv, while it works and amdvlk, I took a look, and it seems like the dynamic UBOs are set with size 32, while the matrices that should be in them are 64 bytes big.

In particular in Renderer.cpp, you use sizeof(DynamicUniformBufferData) a number of times, which is just 4 pointers 32 bytes on a 64-bit platform), you really want sizeof(glm::mat4).

With that you at least get a reasonable image on radv, though the shadows look a bit grainy still.

**Comment by janhsimon** [comment]
Thank you very much @BNieuwenhuizen for spotting this mistake. I have just pushed an update that addresses the issue. Cheers!
