### ISSUE TITLE
Failed to create descriptor

### ISSUE THREAD

**Issue by tiantian20007** [janhsimon/Makma#5]
Got this runtime error after successfully build and launch:
Unable to allocate 5 descriptors of type VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER from pool 0x205. This pool only has 0 descriptors of the type remaining. The spec valid usage text states 'descriptorPool' must have enough free descriptor capacity  remaining to allocate the descriptors sets of the specified layouts

**Comment by janhsimon** [comment]
Huh, that's the first time this error has come up. What GPU are you on? Also, just to be on the safe side, I just pushed an update that prints out a list of all Vulkan-supporting GPUs on launch and which one the program picked.

**Comment by tiantian20007** [comment]
GeForce GTX 970

**Comment by janhsimon** [comment]
It's been almost 3 years, but this should be fixed now. ;)

I will close this issue, but feel free to open a new issue if you're still interested in the project and still get the same error.
